---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercícios - Predação

**Dados iniciais:**


| Parâmetro    | Valor    | Descrição    |
|---------------- | --------------- | --------------- |
| P0    | 300    | tamanho inicial da população de predadores    |
| V0    | 900    | tamanho inicial da população de presas    |
| r   | 0,3   | taxa de crescimento intrínseco das presas   |
| c *ou* α   | 0,001  | eficiência de captura  |
| a *ou* β  | 0,001  | eficiência de conversão  |
| m *ou* q   | 0,06  | taxa de mortalidade do predador  |
| t   | 100  | número de passos de tempo decorridos  |



**1)** Reduza a taxa de crescimento intrínseco das vítimas para 0,1. O que acontece com a população de vítimas e a de predadores, em relação a seus números mínimos e máximos e o tempo dos ciclos?


**2)** Agora mude para r = 0,01 e t = 300. O que acontece com as populações, em relação a seus valores mínimos? O que teria acontecido de diferente na natureza e como isso é diferente do modelo?

**3)** O que você espera que aconteceria com a população de predadores, na vida real, caso fatores antrópicos como caça e destruição de habitat diminuísse a taxa de crescimento intrínseco das vítimas? Se fosse um mesopredador, o que mais poderia acontecer no ecossistema?